# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Animal Kingdom API

on:
  push:
    branches:
      - main
 #   paths:
  #    - 'AnimalKingdom.API/**'
   #   - 'AnimalKingdom.Shared/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
 #   paths:
  #    - 'AnimalKingdom.API/**'
   #   - 'AnimalKingdom.Shared/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: AnimalKingdom.API

      - name: Install EF Core tools
        run: dotnet tool install --global dotnet-ef

      - name: Check if Connection String is available
        run: |
          if [ -z "$ConnectionStrings__AnimalKingdom" ]; then
            echo "❌ Connection string is missing"
            exit 1
          else
            echo "✅ Connection string is set, length: ${#ConnectionStrings__AnimalKingdom}"
            echo "Prefix (safe to show): ${ConnectionStrings__AnimalKingdom:0:10}********"
          fi
        shell: bash
        env:
          ConnectionStrings__AnimalKingdom: ${{ secrets.OVAWATCH_DB_CONNECTION }}


      - name: Run EF Core Migrations
        run: dotnet ef database update
        working-directory: AnimalKingdom.API  # Ensure correct directory for appsettings
        env:
          ASPNETCORE_ENVIRONMENT: Production  # Optional: Explicitly set environment
          ConnectionStrings__AnimalKingdom: ${{ secrets.PROD_CONNECTION_STRING }}

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"
        working-directory: AnimalKingdom.API

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FFEEAE505BAD4E77897D8ABBAC842BBA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5D35A9E706C74BB2B4741BF6AE63BE5D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A9FF32AC7C7D4BEF8C863C6E6DCD2521 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'animalkingdom'
          slot-name: 'Production'
          package: .
